version: '3.8'

services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - endee_data:/app/data

volumes:
  endee_data: